### ISSUE TITLE
Support link-to query params

### ISSUE THREAD

**Issue by vasilakisfil** [twbrandt/ember-simple-pagination#1]
First of all congrats for the addon. We are using this in 2 productions sites and I think this is how future ember-data-related addons should be made: adapter-agnostic. Not to the topic:

What I would like to see is a `linked-to` integration somehow (https://guides.emberjs.com/v2.9.0/routing/query-params/#toc_link-to-helper). Sometimes it's important to have the page params in the url.

**Comment by vasilakisfil** [comment]
Nevermind! I solved it using `transitionTo`: https://guides.emberjs.com/v2.9.0/routing/query-params/#toc_transitionto

Once again congrats for this simple yet powerful addon.

**Comment by twbrandt** [comment]
Thanks. I am glad you find it useful.

**Comment by williamweckl** [comment]
I think this is still important because of SEO.
My pagination links are being rendered by server side as the example below:
```
<li class="page-number">
    <a href="#" data-ember-action="" data-ember-action-989="989">
        2
    </a>
</li>
```

The problem is that google and other search engines will not map my pages, and only the first page results will be indexed...
