### ISSUE TITLE
help first timers avoid not seeing pagination output (due to setting pageNumber to 0)

### ISSUE THREAD

**Issue by zsoldosp** [twbrandt/ember-simple-pagination#4]
As a first time user to the addon, I got bit by the fact that README doesn't specify whether pageNumber is 0 or 1 index based.

I only figured this out by going through the addon's own code.

I'm opening an issue because I'm not sure of what the best solution would be. Some ideas:

* add to the readme that it starts from 1
* explicitly state in the readme when pagination is not displayed
* provide more debug output when
  * explicit component parameter `debug=true`
  * when `ember-cli` environment is `development`
  * the debug output could be
     * `console.debug`
     * a `title` attribute to the element
     * other :)

**Comment by twbrandt** [comment]
I've updated `README`.

**Comment by zsoldosp** [comment]
Thank you!
