### ISSUE TITLE
Page Number show NaN

### ISSUE THREAD

**Issue by l2radamanthys** [twbrandt/ember-simple-pagination#8]
Page number show NaN

```
   <div class="pa3">
      {{simple-pagination
          recordCount=transacciones.lastSuccessful.value.meta.pagination.count
          pageSize=pageSize
          pageNumber=numeroPagina
          onPageSelect=(action "cambiarPagina")}}
    </div>
```
[preview](https://imgur.com/a/POmt4Vv)

**Comment by twbrandt** [comment]
The page numbers are calculated based on the `recordCount`, `pageSize`, and `pageNumber`. If any of those values being passed to the component are not numbers, you will see the result as `NaN`. Please verify that `recordCount`, `pageSize`, and `pageNumber` are valid integers.
